spring:
  application:
    name: Spring-Framework

  datasource:
    url: jdbc:mysql://localhost:3306/accountdb
    username: root
    password: P@$$w0rdv1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false